# site settings
title: KAP1
subtitle: by Marcus de Heus
email: info@kap1consulting.de
description: Top Talents for Corporate Functions.
url: # the base hostname & protocol for your site
author:
street_address: Koenigsallee 14
city: Duesseldorf
state: NRW
zip_code: 40221
country: Germany
phone: +49 211 13866-436

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/marcusdeheus
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+marcusdeheus
  Instagram:
  LinkedIn: https://www.linkedin.com/in/marcus-de-heus-73a4831/
  Xing: https://www.xing.com/profile/Marcus_deHeus/cv 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- elements.md
